### ISSUE TITLE
bug: Handle when no compatible hardware detected

### ISSUE THREAD

**Issue by tim-hm** [canonical/firmware-updater#278]
If there is no compatible hardware detected then the firmware-updater displays a spinner indefinitely and logs an error. This is on `Linux noble 6.8.0-22-generic #22-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr  5 02:52:09 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux` and running `latest/candidate: 0+git.999a4d9 2024-04-09 (126)`.

## Spinner displayed indefinitely

<img width="1009" alt="image" src="https://github.com/canonical/firmware-updater/assets/1335525/befc855c-a55b-4e95-9510-da76d7c50fd7">

## Error from journalctl

```
Apr 09 15:30:29 noble firmware-updater.firmware-updater-app[3770]: flutter: ERROR firmware-updater: Logging to /snap/firmware-updater/126/bin/.firmware-updater/firmware-updater.log failed (Creation failed)
Apr 09 15:30:29 noble dbus-daemon[1083]: [system] Activating via systemd: service name='org.freedesktop.fwupd' unit='fwupd.service' requested by ':1.154' (uid=1000 pid=3770 comm="/snap/firmware-updater/126/bin/firmware-updater --" label="snap.firmware-updater.firmware-updater-app (enforce)")
Apr 09 15:30:31 noble firmware-updater.firmware-updater-app[3770]: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FwupdNothingToDoException: No detected devices
Apr 09 15:30:31 noble firmware-updater.firmware-updater-app[3770]: #0      FwupdClient._callMethod (package:fwupd/src/fwupd_client.dart:555)
Apr 09 15:30:31 noble firmware-updater.firmware-updater-app[3770]: <asynchronous suspension>
Apr 09 15:30:31 noble firmware-updater.firmware-updater-app[3770]: #1      FwupdClient.getDevices (package:fwupd/src/fwupd_client.dart:168)
Apr 09 15:30:31 noble firmware-updater.firmware-updater-app[3770]: <asynchronous suspension>
```

## Expected behaviour

- If there is no eligible/compatible hardware detected the app should display a simple message, perhaps with an icon, to capture this state.
- The log message should probably just be warn in this case as well

**Comment by tim-hm** [comment]
This was addressed previously in https://github.com/canonical/firmware-updater/pull/165. Perhaps we're now seeing this since its an arm build of the app?
